array = [2, 4, ['a', 'b'], nil, 4, 'c']

puts array
puts array.length
puts array.size
puts array.reverse
puts array.reverse!
puts array
puts array.shuffle
puts array.shuffle!
puts array
puts array.uniq
puts array.uniq!
puts array
puts array.compact
puts array.compact!
puts array
puts array.flatten
puts array.flatten!
puts array
puts array.include?(2)
puts array.include?(1)
puts array.delete_at(1)
puts array
puts array.delete('c')
puts array
puts [1,2,3,4].join(',')
puts [1,2,3,4].join
puts "1,2,3,4".split(',')
